// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsGroupDao is the data access object for the table bbs_group.
// You can define custom methods on it to extend its functionality as needed.
type bbsGroupDao struct {
	*internal.BbsGroupDao
}

var (
	// BbsGroup is a globally accessible object for table bbs_group operations.
	BbsGroup = bbsGroupDao{internal.NewBbsGroupDao()}
)

// Add your custom methods and functionality below.
