// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsThreadTopDao is the data access object for the table bbs_thread_top.
// You can define custom methods on it to extend its functionality as needed.
type bbsThreadTopDao struct {
	*internal.BbsThreadTopDao
}

var (
	// BbsThreadTop is a globally accessible object for table bbs_thread_top operations.
	BbsThreadTop = bbsThreadTopDao{internal.NewBbsThreadTopDao()}
)

// Add your custom methods and functionality below.
