// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsCacheDao is the data access object for the table bbs_cache.
// You can define custom methods on it to extend its functionality as needed.
type bbsCacheDao struct {
	*internal.BbsCacheDao
}

var (
	// BbsCache is a globally accessible object for table bbs_cache operations.
	BbsCache = bbsCacheDao{internal.NewBbsCacheDao()}
)

// Add your custom methods and functionality below.
