// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsPostDao is the data access object for the table bbs_post.
// You can define custom methods on it to extend its functionality as needed.
type bbsPostDao struct {
	*internal.BbsPostDao
}

var (
	// BbsPost is a globally accessible object for table bbs_post operations.
	BbsPost = bbsPostDao{internal.NewBbsPostDao()}
)

// Add your custom methods and functionality below.
