// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsSessionDao is the data access object for the table bbs_session.
// You can define custom methods on it to extend its functionality as needed.
type bbsSessionDao struct {
	*internal.BbsSessionDao
}

var (
	// BbsSession is a globally accessible object for table bbs_session operations.
	BbsSession = bbsSessionDao{internal.NewBbsSessionDao()}
)

// Add your custom methods and functionality below.
