// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsThreadDao is the data access object for the table bbs_thread.
// You can define custom methods on it to extend its functionality as needed.
type bbsThreadDao struct {
	*internal.BbsThreadDao
}

var (
	// BbsThread is a globally accessible object for table bbs_thread operations.
	BbsThread = bbsThreadDao{internal.NewBbsThreadDao()}
)

// Add your custom methods and functionality below.
