// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsForumDao is the data access object for the table bbs_forum.
// You can define custom methods on it to extend its functionality as needed.
type bbsForumDao struct {
	*internal.BbsForumDao
}

var (
	// BbsForum is a globally accessible object for table bbs_forum operations.
	BbsForum = bbsForumDao{internal.NewBbsForumDao()}
)

// Add your custom methods and functionality below.
