// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsForumAccessDao is the data access object for the table bbs_forum_access.
// You can define custom methods on it to extend its functionality as needed.
type bbsForumAccessDao struct {
	*internal.BbsForumAccessDao
}

var (
	// BbsForumAccess is a globally accessible object for table bbs_forum_access operations.
	BbsForumAccess = bbsForumAccessDao{internal.NewBbsForumAccessDao()}
)

// Add your custom methods and functionality below.
