// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsMypostDao is the data access object for the table bbs_mypost.
// You can define custom methods on it to extend its functionality as needed.
type bbsMypostDao struct {
	*internal.BbsMypostDao
}

var (
	// BbsMypost is a globally accessible object for table bbs_mypost operations.
	BbsMypost = bbsMypostDao{internal.NewBbsMypostDao()}
)

// Add your custom methods and functionality below.
