// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsKvDao is the data access object for the table bbs_kv.
// You can define custom methods on it to extend its functionality as needed.
type bbsKvDao struct {
	*internal.BbsKvDao
}

var (
	// BbsKv is a globally accessible object for table bbs_kv operations.
	BbsKv = bbsKvDao{internal.NewBbsKvDao()}
)

// Add your custom methods and functionality below.
