// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsAttachDao is the data access object for the table bbs_attach.
// You can define custom methods on it to extend its functionality as needed.
type bbsAttachDao struct {
	*internal.BbsAttachDao
}

var (
	// BbsAttach is a globally accessible object for table bbs_attach operations.
	BbsAttach = bbsAttachDao{internal.NewBbsAttachDao()}
)

// Add your custom methods and functionality below.
