// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsTableDayDao is the data access object for the table bbs_table_day.
// You can define custom methods on it to extend its functionality as needed.
type bbsTableDayDao struct {
	*internal.BbsTableDayDao
}

var (
	// BbsTableDay is a globally accessible object for table bbs_table_day operations.
	BbsTableDay = bbsTableDayDao{internal.NewBbsTableDayDao()}
)

// Add your custom methods and functionality below.
