// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsModlogDao is the data access object for the table bbs_modlog.
// You can define custom methods on it to extend its functionality as needed.
type bbsModlogDao struct {
	*internal.BbsModlogDao
}

var (
	// BbsModlog is a globally accessible object for table bbs_modlog operations.
	BbsModlog = bbsModlogDao{internal.NewBbsModlogDao()}
)

// Add your custom methods and functionality below.
