// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsMythreadDao is the data access object for the table bbs_mythread.
// You can define custom methods on it to extend its functionality as needed.
type bbsMythreadDao struct {
	*internal.BbsMythreadDao
}

var (
	// BbsMythread is a globally accessible object for table bbs_mythread operations.
	BbsMythread = bbsMythreadDao{internal.NewBbsMythreadDao()}
)

// Add your custom methods and functionality below.
