// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsQueueDao is the data access object for the table bbs_queue.
// You can define custom methods on it to extend its functionality as needed.
type bbsQueueDao struct {
	*internal.BbsQueueDao
}

var (
	// BbsQueue is a globally accessible object for table bbs_queue operations.
	BbsQueue = bbsQueueDao{internal.NewBbsQueueDao()}
)

// Add your custom methods and functionality below.
