// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsSessionDataDao is the data access object for the table bbs_session_data.
// You can define custom methods on it to extend its functionality as needed.
type bbsSessionDataDao struct {
	*internal.BbsSessionDataDao
}

var (
	// BbsSessionData is a globally accessible object for table bbs_session_data operations.
	BbsSessionData = bbsSessionDataDao{internal.NewBbsSessionDataDao()}
)

// Add your custom methods and functionality below.
