// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/0x3st/XiuGo/internal/dao/internal"
)

// bbsUserDao is the data access object for the table bbs_user.
// You can define custom methods on it to extend its functionality as needed.
type bbsUserDao struct {
	*internal.BbsUserDao
}

var (
	// BbsUser is a globally accessible object for table bbs_user operations.
	BbsUser = bbsUserDao{internal.NewBbsUserDao()}
)

// Add your custom methods and functionality below.
