// Command genplugins scans ./plugins/* directories and writes
// internal/plugin/registry/zz_generated.go with blank imports.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	modulePath = "github.com/0x3st/XiuGo"
	pluginsDir = "plugins"
	outFile    = "internal/plugin/registry/zz_generated.go"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fail(err)
	}
	// allow run from repo root
	dir := filepath.Join(root, pluginsDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			entries = nil
		} else {
			fail(err)
		}
	}
	var ids []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, ".") || name == "README.md" {
			continue
		}
		// must contain at least one .go file
		sub := filepath.Join(dir, name)
		hasGo := false
		_ = filepath.Walk(sub, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return nil
			}
			if strings.HasSuffix(info.Name(), ".go") && !strings.HasSuffix(info.Name(), "_test.go") {
				hasGo = true
			}
			return nil
		})
		if hasGo {
			ids = append(ids, name)
		}
	}
	sort.Strings(ids)

	var b strings.Builder
	b.WriteString("// Code generated by hack/genplugins; DO NOT EDIT.\n")
	b.WriteString("// Run: go generate ./internal/plugin/registry\n\n")
	b.WriteString("package registry\n\n")
	if len(ids) == 0 {
		b.WriteString("// No drop-in plugins under plugins/ yet.\n")
	} else {
		b.WriteString("import (\n")
		for _, id := range ids {
			b.WriteString(fmt.Sprintf("\t_ %q\n", modulePath+"/plugins/"+id))
		}
		b.WriteString(")\n")
	}
	out := filepath.Join(root, outFile)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("genplugins: wrote %s (%d plugin(s): %s)\n", outFile, len(ids), strings.Join(ids, ", "))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
